import { PlayArrowOutlined, SecurityOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardContent, Chip, Grid, Stack, Typography } from '@mui/material';
import type { ServiceStatus } from '../../../shared/api/zapretyd';
import { useTranslation } from '../../../shared/i18n';

export function OverviewPage({ status, onService }: { status?: ServiceStatus; onService: () => void }) {
  const { t } = useTranslation();
  const running = status?.serviceRunning && status.winwsRunning;
  return <Stack spacing={3}><Box><Typography variant="h3">{t('overview.title')}</Typography><Typography color="text.secondary" mt={1}>{t('overview.subtitle')}</Typography></Box><Card sx={{ bgcolor: running ? 'primary.main' : 'background.paper', color: running ? 'primary.contrastText' : 'text.primary' }}><CardContent sx={{ p: 4 }}><Stack direction={{ xs: 'column', sm: 'row' }} alignItems="center" justifyContent="space-between" spacing={3}><Box><Chip label={running ? t('overview.active') : t('overview.inactive')} color={running ? 'success' : 'default'} sx={{ mb: 2 }} /><Typography variant="h4">{running ? t('overview.running') : t('overview.stopped')}</Typography><Typography sx={{ opacity: .8, mt: 1 }}>{status?.activeStrategy ? t('overview.strategy', { name: status.activeStrategy }) : t('overview.pickStrategyHint')}</Typography></Box><SecurityOutlined sx={{ fontSize: 92, opacity: .75 }} /></Stack></CardContent></Card><Grid container spacing={2}><Grid size={{ xs: 12, md: 4 }}><Card><CardContent><Typography color="text.secondary">{t('overview.serviceCard')}</Typography><Typography variant="h5" mt={1}>{status?.serviceRunning ? t('overview.runningState') : t('overview.stoppedState')}</Typography></CardContent></Card></Grid><Grid size={{ xs: 12, md: 4 }}><Card><CardContent><Typography color="text.secondary">{t('overview.windivert')}</Typography><Typography variant="h5" mt={1}>{status?.windivertRunning ? t('overview.windivertActive') : t('overview.windivertInactive')}</Typography></CardContent></Card></Grid><Grid size={{ xs: 12, md: 4 }}><Card><CardContent><Typography color="text.secondary">{t('overview.adminRights')}</Typography><Typography variant="h5" mt={1}>{status?.isAdmin ? t('overview.adminGranted') : t('overview.adminMissing')}</Typography></CardContent></Card></Grid></Grid>{!status?.isAdmin && <Alert severity="warning" action={<Button color="inherit" size="small" onClick={onService}>{t('overview.openService')}</Button>}>{t('overview.adminWarning')}</Alert>}<Button startIcon={<PlayArrowOutlined />} sx={{ alignSelf: 'flex-start' }} onClick={onService}>{t('overview.pickStrategy')}</Button></Stack>;
}
