import { DeleteOutline, DownloadOutlined, FolderOpenOutlined, RefreshOutlined } from '@mui/icons-material';
import { Alert, Box, Button, Card, CardActions, CardContent, Chip, CircularProgress, Stack, Typography } from '@mui/material';
import type { InstalledVersion, ReleaseInfo } from '../../../shared/api/zapretyd';
import { useTranslation } from '../../../shared/i18n';
import { formatBytes, formatDate } from '../../../shared/lib/format';

export function VersionsPage({ versions, latest, busy, error, onCheck, onInstall, onRemove, onOpen }: { versions: InstalledVersion[]; latest?: ReleaseInfo; busy: boolean; error?: string; onCheck: () => void; onInstall: () => void; onRemove: (tag: string) => void; onOpen: (path: string) => void }) {
  const { t } = useTranslation();
  return <Stack spacing={3}><Box display="flex" justifyContent="space-between" gap={2} alignItems="center"><Box><Typography variant="h3">{t('versions.title')}</Typography><Typography color="text.secondary" mt={1}>{t('versions.subtitle')}</Typography></Box><Button variant="outlined" startIcon={<RefreshOutlined />} onClick={onCheck} disabled={busy}>{t('versions.check')}</Button></Box>{error && <Alert severity="error">{error}</Alert>}{latest && <Card sx={{ borderColor: latest.isNewerThanInstalled ? 'primary.main' : undefined }}><CardContent><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2}><Box><Typography variant="overline">{t('versions.latestRelease')}</Typography><Typography variant="h5">{latest.tag}</Typography><Typography color="text.secondary">{t('versions.published', { date: formatDate(latest.publishedAt), size: formatBytes(latest.size) })}</Typography></Box>{latest.isNewerThanInstalled ? <Button startIcon={busy ? <CircularProgress size={18} /> : <DownloadOutlined />} disabled={busy} onClick={onInstall}>{t('versions.downloadInstall')}</Button> : <Chip label={t('versions.alreadyInstalled')} color="success" />}</Stack></CardContent></Card>}<Stack spacing={2}>{versions.length === 0 && <Alert severity="info">{t('versions.noVersions')}</Alert>}{versions.map((version) => <Card key={version.tag}><CardContent><Stack direction="row" justifyContent="space-between" alignItems="start"><Box><Typography variant="h6">{version.tag} {version.isActive && <Chip label={t('versions.active')} color="primary" size="small" sx={{ ml: 1 }} />}</Typography><Typography color="text.secondary" variant="body2">{t('versions.installed', { date: formatDate(version.installedAt), size: formatBytes(version.size) })}</Typography><Typography color="text.secondary" variant="caption">{version.path}</Typography></Box></Stack></CardContent><CardActions><Button variant="text" startIcon={<FolderOpenOutlined />} onClick={() => onOpen(version.path)}>{t('versions.open')}</Button><Button variant="text" color="error" disabled={version.isActive} startIcon={<DeleteOutline />} onClick={() => onRemove(version.tag)}>{t('versions.remove')}</Button></CardActions></Card>)}</Stack></Stack>;
}
